# Generated by Django 4.2.3 on 2023-10-06 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vyaparapp', '0005_rename_contact_number_company_details_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_details',
            name='gst_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
