# Generated by Django 4.2.3 on 2023-10-06 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vyaparapp', '0006_company_details_gst_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_details',
            name='contact',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
