# Generated by Django 4.2.3 on 2023-10-08 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vyaparapp', '0007_company_details_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_details',
            name='Action',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='staff_details',
            name='Action',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
