# Generated by Django 4.2.3 on 2023-10-15 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vyaparapp', '0010_payment_terms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment_terms',
            name='days',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
