# Generated by Django 4.2.3 on 2023-10-15 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vyaparapp', '0011_alter_payment_terms_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_details',
            name='Company_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
