# Generated by Django 4.2.3 on 2023-10-15 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vyaparapp', '0013_alter_company_details_dateperiod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_details',
            name='dateperiod',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
