# Generated by Django 4.2.3 on 2023-10-15 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vyaparapp', '0014_alter_company_details_dateperiod'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company_details',
            name='dateperiod',
        ),
    ]
