# Generated by Django 4.2.3 on 2023-10-15 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vyaparapp', '0016_company_details_dateperiod_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='dateperiod',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vyaparapp.payment_terms'),
        ),
    ]
