# Generated by Django 4.2.3 on 2023-10-15 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vyaparapp', '0017_alter_company_dateperiod'),
    ]

    operations = [
        migrations.DeleteModel(
            name='company_details',
        ),
    ]
