# Generated by Django 4.2.3 on 2023-10-15 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vyaparapp', '0019_company_details'),
    ]

    operations = [
        migrations.DeleteModel(
            name='company_details',
        ),
    ]
