# Generated by Django 4.2.3 on 2023-10-15 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vyaparapp', '0021_modules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modules',
            name='sales_invoice',
            field=models.CharField(default=0, max_length=100, null=True),
        ),
    ]
