# Generated by Django 4.2.3 on 2023-10-16 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vyaparapp', '0022_alter_modules_sales_invoice'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='modules',
            new_name='modules_list',
        ),
    ]
