# Generated by Django 4.2.3 on 2023-10-25 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vyaparapp', '0023_rename_modules_modules_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='modules_list',
            name='update_action',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
