# Generated by Django 4.2.3 on 2023-10-25 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vyaparapp', '0025_modules_list_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff_details',
            name='contact',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
