# Generated by Django 4.2.3 on 2023-10-28 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vyaparapp', '0027_rename_action_company_distributor_approval_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='distributors_details',
            old_name='payment_terms',
            new_name='payment_term',
        ),
    ]
