# Generated by Django 4.2.3 on 2023-10-28 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vyaparapp', '0028_rename_payment_terms_distributors_details_payment_term'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributors_details',
            name='Log_Action',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
