# Generated by Django 4.2.3 on 2023-10-30 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vyaparapp', '0029_distributors_details_log_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='reg_action',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
