# Generated by Django 4.2.3 on 2023-10-30 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vyaparapp', '0031_alter_company_reg_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='reg_action',
            field=models.CharField(blank=True, default='self', max_length=255, null=True),
        ),
    ]
