# Generated by Django 4.2.3 on 2023-10-30 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vyaparapp', '0032_alter_company_reg_action'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='reg_action',
        ),
    ]
